apiVersion: apps/v1
kind: Deployment
metadata:
  name: faleconosco
  namespace: coletaconsciente
  labels:
    app: faleconosco
spec:
  replicas: 2
  selector:
    matchLabels:
      app: faleconosco
  template:
    metadata:
      labels:
        app: faleconosco
    spec:
      containers:
        - name: faleconosco
          image: jmarquessilva/faleconosco:1.1
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: faleconosco-configmap
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
              httpGet:
                path: /actuator/health
                port: 8082
              initialDelaySeconds: 15
              periodSeconds: 20
          resources: {}