apiVersion: v1
kind: Service
metadata:
  name: faleconosco-svc
  namespace: coletaconsciente
  labels:
    app: faleconosco
spec:
  type: ClusterIP
  selector:
    app: faleconosco
  ports:
    - port: 8082
      targetPort: 8082