apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: coletaconsciente
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: jmarquessilva/user:1.2
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: user-configmap
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
              httpGet:
                path: /actuator/health
                port: 8080
              initialDelaySeconds: 15
              periodSeconds: 20
          resources: {}