apiVersion: apps/v1
kind: Deployment
metadata:
  name: location
  namespace: coletaconsciente
  labels:
    app: location
spec:
  replicas: 2
  selector:
    matchLabels:
      app: location
  template:
    metadata:
      labels:
        app: location
    spec:
      containers:
        - name: location
          image: jmarquessilva/location:1.1
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: location-configmap
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
              httpGet:
                path: /actuator/health
                port: 8083
              initialDelaySeconds: 15
              periodSeconds: 20
          resources: {}