apiVersion: apps/v1
kind: Deployment
metadata:
  name: location
  namespace: coletaconsciente
  labels:
    app: location
spec:
  replicas: 2
  selector:
    matchLabels:
      app: location
  template:
    metadata:
      labels:
        app: location
    spec:
      containers:
        - name: location
          image: jmarquessilva/location:1.0
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: location-configmap