apiVersion: v1
kind: Service
metadata:
  name: location-svc
  namespace: coletaconsciente
  labels:
    app: location
spec:
  type: LoadBalancer
  selector:
    app: location
  ports:
    - port: 8083
      targetPort: 8083
